NumPy

PANDAS

In [65]:
import pandas as pd
import numpy as np

In [66]:
df=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['row1','row2','row3','row4','row5'],columns=['c1','c2','c3','c4'])

In [67]:
df.head()

      c1  c2  c3  c4
row1   0   1   2   3
row2   4   5   6   7
row3   8   9  10  11
row4  12  13  14  15
row5  16  17  18  19

In [68]:
df.to_csv('test.csv')

In [69]:
##accesing the element
##1. loc  2.iloc
df.loc['row2']

c1    4
c2    5
c3    6
c4    7
Name: row2, dtype: int32

In [70]:
## type
type(df.loc['row2'])

pandas.core.series.Series

In [71]:
df.iloc[0:2,0:4]

      c1  c2  c3  c4
row1   0   1   2   3
row2   4   5   6   7

In [72]:
##data frame to array
df.iloc[:,:].values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [73]:
## check null value
df.isnull().sum()

c1    0
c2    0
c3    0
c4    0
dtype: int64

In [74]:
df['c1'].value_counts()

c1
0     1
4     1
8     1
12    1
16    1
Name: count, dtype: int64

In [75]:
df['c1'].unique()

array([ 0,  4,  8, 12, 16])

In [76]:
df=pd.read_csv('mercedesbenz.csv')

In [77]:
df.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB

In [79]:
df.describe()

,ID,y,X10,X11,X12,X13,X14,X15,X16,X17,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
count,4209.000000,4209.000000,4209.000000,4209.0,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,...,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000
mean,4205.960798,100.669318,0.013305,0.0,0.075077,0.057971,0.428130,0.000475,0.002613,0.007603,...,0.318841,0.057258,0.314802,0.020670,0.009503,0.008078,0.007603,0.001663,0.000475,0.001426
std,2437.608688,12.679381,0.114590,0.0,0.263547,0.233716,0.494867,0.021796,0.051061,0.086872,...,0.466082,0.232363,0.464492,0.142294,0.097033,0.089524,0.086872,0.040752,0.021796,0.037734
min,0.000000,72.110000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2095.000000,90.820000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4220.000000,99.150000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,6314.000000,109.010000,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,8417.000000,265.320000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [80]:
from io import StringIO,BytesIO

In [81]:
data=('col1,col2,col3\n'
      'x,y,1\n'
      'a,b,2\n'
      'c,d,3')

In [82]:
type(data)

str

In [83]:
pd.read_csv(StringIO(data))

  col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [84]:
##read a specific colunm
df=pd.read_csv(StringIO(data), usecols=['col1','col2'])

In [85]:
df.head()

  col1 col2
0    x    y
1    a    b
2    c    d

In [86]:
## specifying column datatype
data=('a,b,c,d\n'
      '1,2,3,4\n'
      '5,6,7,8\n'
      '9,10,11,12')

In [87]:
print( data)

a,b,c,d
1,2,3,4
5,6,7,8
9,10,11,12

In [88]:
df=pd.read_csv(StringIO(data),dtype=object )

In [89]:
df

   a   b   c   d
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [90]:
df['a']

0    1
1    5
2    9
Name: a, dtype: object

In [91]:
df=pd.read_csv(StringIO(data),dtype={'b':int,'c':float,'d':'int64'} )

In [92]:
df.dtypes

a      int64
b      int32
c    float64
d      int64
dtype: object

In [93]:
data1=('a,b,c\n'
      '4,apple,bat,\n'
      '8,oreng,cow\n')

In [94]:
pd.read_csv(StringIO(data),index_col=1)

       a    b   c
apple  4  bat NaN
oreng  8  cow NaN

In [95]:
pd.read_csv(StringIO(data),index_col=False)

   a      b    c
0  4  apple  bat
1  8  oreng  cow

Read Json files

In [96]:
import json

In [108]:
data='{"emp_name":"arshad","email":"arshad@gmail.com","job_profile":[{"title1":"team lead","title2":"manager"}]}'
df1=pd.read_json(data)

C:\Users\arsha\AppData\Local\Temp\ipykernel_14908\3694837629.py:2: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df1=pd.read_json(data)

In [103]:
df=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data',header=None)

In [104]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [105]:
df.to_csv('wine.csv')

In [109]:
df1.to_json()

'{"emp_name":{"0":"arshad"},"email":{"0":"arshad@gmail.com"},"job_profile":{"0":{"title1":"team lead","title2":"manager"}}}'

In [111]:
df1.to_json(orient="records")

'[{"emp_name":"arshad","email":"arshad@gmail.com","job_profile":{"title1":"team lead","title2":"manager"}}]'

reading HTML content

In [114]:
url='https://www.fdic.gov/bank/individual/failed/banklist.html'
dfs=pd.read_html(url)

In [115]:
dfs[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
1,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
2,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
3,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
4,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
5,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
6,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
7,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
8,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
9,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
10,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
11,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
12,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
13,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
14,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
15,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
16,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
17,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
18,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
19,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
20,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
21,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
22,First NBC Bank,New Orleans,Louisiana,58302,Whitney Bank,"April 28, 2017",10526
23,Proficio Bank,Cottonwood Heights,Utah,35495,Cache Valley Bank,"March 3, 2017",10525
24,Seaway Bank and Trust Company,Chicago,Illinois,19328,State Bank of Texas,"January 27, 2017",10524

Reading exel files

In [116]:
df_exel=pd.read_exel('excel_sample.xlsx')

AttributeError: module 'pandas' has no attribute 'read_exel'

pickling

In [118]:
df_exel.to_pickle('df_exel')

AttributeError: 'str' object has no attribute 'to_pickle'