In [4]:
import pandas as pd
import numpy as np

In [9]:
df=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['row1','row2','row3','row4','row5'],columns=['c1','c2','c3','c4'])

In [10]:
df.head()

      c1  c2  c3  c4
row1   0   1   2   3
row2   4   5   6   7
row3   8   9  10  11
row4  12  13  14  15
row5  16  17  18  19

In [12]:
df.to_csv('test.csv')

In [17]:
##accesing the element
##1. loc  2.iloc
df.loc['row2']

c1    4
c2    5
c3    6
c4    7
Name: row2, dtype: int32

In [16]:
## type
type(df.loc['row2'])

pandas.core.series.Series

In [21]:
df.iloc[0:2,0:4]

      c1  c2  c3  c4
row1   0   1   2   3
row2   4   5   6   7

In [22]:
##data frame to array
df.iloc[:,:].values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [23]:
## check null value
df.isnull().sum()

c1    0
c2    0
c3    0
c4    0
dtype: int64

In [28]:
df['c1'].value_counts()

c1
0     1
4     1
8     1
12    1
16    1
Name: count, dtype: int64

In [29]:
df['c1'].unique()

array([ 0,  4,  8, 12, 16])

In [30]:
df=pd.read_csv('mercedesbenz.csv')

In [31]:
df.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB

In [34]:
df.describe()

,ID,y,X10,X11,X12,X13,X14,X15,X16,X17,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
count,4209.000000,4209.000000,4209.000000,4209.0,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,...,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000
mean,4205.960798,100.669318,0.013305,0.0,0.075077,0.057971,0.428130,0.000475,0.002613,0.007603,...,0.318841,0.057258,0.314802,0.020670,0.009503,0.008078,0.007603,0.001663,0.000475,0.001426
std,2437.608688,12.679381,0.114590,0.0,0.263547,0.233716,0.494867,0.021796,0.051061,0.086872,...,0.466082,0.232363,0.464492,0.142294,0.097033,0.089524,0.086872,0.040752,0.021796,0.037734
min,0.000000,72.110000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2095.000000,90.820000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4220.000000,99.150000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,6314.000000,109.010000,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,8417.000000,265.320000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [35]:
from io import StringIO,BytesIO

In [36]:
data=('col1,col2,col3\n'
      'x,y,1\n'
      'a,b,2\n'
      'c,d,3')

In [37]:
type(data)

str

In [38]:
pd.read_csv(StringIO(data))

  col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [41]:
##read a specific colunm
df=pd.read_csv(StringIO(data), usecols=['col1','col2'])

In [43]:
df.head()

  col1 col2
0    x    y
1    a    b
2    c    d

In [44]:
## specifying column datatype
data=('a,b,c,d\n'
      '1,2,3,4\n'
      '5,6,7,8\n'
      '9,10,11,12')

In [46]:
print( data)

a,b,c,d
1,2,3,4
5,6,7,8
9,10,11,12

In [56]:
df=pd.read_csv(StringIO(data),dtype=object )

In [57]:
df

   a   b   c   d
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [58]:
df['a']

0    1
1    5
2    9
Name: a, dtype: object

In [60]:
df=pd.read_csv(StringIO(data),dtype={'b':int,'c':float,'d':'int64'} )

In [65]:
df.dtypes

a      int64
b      int32
c    float64
d      int64
dtype: object